name: Game Notifier
on:
  schedule:
    - cron: '0 4,16 * * *'  # 10AM & 10PM IST
  workflow_dispatch:
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python & Run Main
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: |
          pip install -r requirements.txt || true
          python main.py

      - name: Setup Node & Send Emails
        if: success()
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - run: |
          npm install nodemailer
          node mailer.js
        env:
          BREVO_KEY: ${{ secrets.BREVO_KEY }}