name: Free Game Notifier

on:
  schedule:
    - cron: '30 4 * * *'   # 10:00 IST daily (UTC 04:30)
    - cron: '30 16 * * *'  # 22:00 IST daily (UTC 16:30)
  workflow_dispatch:

jobs:
  run-and-email:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python deps
        run: pip install -r requirements.txt

      - name: Run scrapers (Python)
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}
          DASHBOARD_LINK: ${{ secrets.DASHBOARD_LINK }}
        run: python main.py

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install nodemailer
        run: npm install nodemailer

      - name: Send emails (Node)
        env:
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
          DASHBOARD_LINK: ${{ secrets.DASHBOARD_LINK }}
          MAX_SUBS: "250"
        run: node mailer.js

      - name: Commit dashboard & drops
        run: |
          git config user.name "game-bot"
          git config user.email "action@github.com"
          git add dashboard/dashboard.html drops.json
          git commit -m "Update dashboard and drops" || echo "No changes to commit"
          git push