name: Free Game Notifier

on:
  schedule:
    # Times in UTC: IST is UTC+5:30
    - cron: '45 2 * * *'   # 08:15 IST
    - cron: '30 10 * * *'  # 16:00 IST
    - cron: '30 16 * * *'  # 22:00 IST
  workflow_dispatch:

jobs:
  run-and-email:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python deps
        run: |
          pip install -r requirements.txt
          playwright install firefox

      - name: Pick random Indian proxy
        run: |
          # Pick one random proxy from the secret list
          echo "$INDIA_PROXIES" | shuf -n 1 > chosen_proxy.txt
          PROXY=$(cat chosen_proxy.txt)
          echo "🎯 Using proxy: $PROXY"

          # Save to environment for later steps
          echo "http_proxy=http://$PROXY" >> $GITHUB_ENV
          echo "https_proxy=http://$PROXY" >> $GITHUB_ENV

          # (Optional) Verify proxy works & geo is India
          echo "Checking proxy location..."
          curl -s --max-time 10 --proxy http://$PROXY ipinfo.io/json || echo "⚠️ Proxy check failed"

      - name: Run scrapers (Python)
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}
          DASHBOARD_LINK: ${{ secrets.DASHBOARD_LINK }}
        run: python main.py

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Node dependencies
        run: npm install

      - name: Send emails (Node) if summary exists
        if: ${{ success() && hashFiles('drop_summary.txt') != '' }}
        env:
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
          DASHBOARD_LINK: ${{ secrets.DASHBOARD_LINK }}
          MAX_SUBS: "250"
        run: |
          if [ ! -s drop_summary.txt ]; then
            echo "No drop_summary.txt or it's empty. Skipping emails."
            exit 0
          fi
          node mailer.js

      - name: Commit dashboard & JSON updates
        if: success()
        run: |
          git config user.name "ServerBlaster"
          git config user.email "gsreejeeth@gmail.com"
          git add dashboard/dashboard.html drops.json game_data.json monthly_archive.json
          git commit -m "Update dashboard, JSON data, and drops" || echo "No changes to commit"
          # Set remote to use PAT explicitly
          git remote set-url origin https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/ServerBlaster/free_game_notifier.git
          # Push to main using PAT
          git push origin HEAD:main
